name: test-and-publish

on: [push]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      postgres2:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5431:5432
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y redis-server
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm version patch
        npm install
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/organizations @userdashboard/storage-redis --no-save
        npm install -g mocha standard
        mkdir -p node_modules/@userdashboard/storage-postgresql
        cp *.js node_modules/@userdashboard/storage-postgresql
        cp *.sql node_modules/@userdashboard/storage-postgresql
        cp -R src/ node_modules/@userdashboard/storage-postgresql/src/
        cp package.json package.json.old
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"deprecated\"\: false/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/organizations\"\] \}}
        echo $PACKAGE > package.json
    - name: Lint (standard.js)
      run: standard src
    - name: Test as shared storage
      run: |
        mocha --file test-helper.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee tests.txt
        TESTS=`cat tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-postgresql"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test as only storage
      run: |
        mocha --file test-helper.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee tests.txt
        TESTS=`cat tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-postgresql"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        ORGANIZATIONS_STORAGE: "@userdashboard/storage-redis"
        ORGANIZATIONS_REDIS_URL: "redis://localhost:6379"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test as module storage
      run: |
        mocha --file test-helper.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee tests.txt
        TESTS=`cat tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
        ORGANIZATIONS_STORAGE: "@userdashboard/storage-postgresql"
        ORGANIZATIONS_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test as primary and separately as module storage
      run: |
        mocha --file test-helper.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee tests.txt
        TESTS=`cat tests.txt`
        if [[ "$TESTS" == *" 1)"* ]]; then
          exit 1
        fi
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-postgresql"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        ORGANIZATIONS_STORAGE: "@userdashboard/storage-postgresql"
        ORGANIZATIONS_DATABASE_URL: "postgres://postgres:postgres@localhost:5431/postgres"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Clean up
      run: |
        rm package.json
        mv package.json.old package.json
    - name: Publish to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }} 